_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "models/CondInst_MS_R_50_3x.pth"
  RESNETS:
    DEPTH: 50
  FCOS:
    NUM_CLASSES: 2
  CONDINST:
    MAX_PROPOSALS: 1000
OUTPUT_DIR: "train_dir/kitti/mots_R50_1x"
INPUT:
  RESIZE_MODE: "fixed"
  FIXED_SIZES_TRAIN: ((384, 1280),)
  FIXED_SIZES_TEST: ((384, 1280),)
  MASK_FORMAT: "bitmask"
DATASETS:
  # TRAIN: ("kitti_mots_train",)
  TRAIN: ("kitti_mots_val",)
  TEST: ("kitti_mots_val",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  OPTIMIZER: "Adam"  # default: SGD
  IMS_PER_BATCH: 32  # 4520 training images, ~283 iters/epoch
  BASE_LR: 1e-4
  WARMUP_ITERS: 0
  # scheduler, 1x
  STEPS: (6000,)
  MAX_ITER: 9000
