_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "models/CondInst_MS_R_50_3x.pth"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MAX_PROPOSALS: 500  # use 500 if SOLVER.IMS_PER_BATCH = 32
OUTPUT_DIR: "train_dir/CondInst_mots_R_50_1x"
INPUT:
  RESIZE_MODE: "fixed"
  # FIXED_SIZES_TRAIN: ((544, 960), (576, 1024), (608, 1088), (640, 1152), (672, 1218), (704, 1282))
  FIXED_SIZES_TRAIN: ((608, 1088),)
  FIXED_SIZES_TEST: ((608, 1088),)
  MASK_FORMAT: "bitmask"
DATASETS:
  TRAIN: ("mots_train_05",)
  TEST: ("mots_val_05",)
  # TRAIN: ("mots_train",)
  # TEST: ()
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  OPTIMIZER: "Adam"  # default: SGD
  IMS_PER_BATCH: 16
  BASE_LR: 1e-4
  WARMUP_ITERS: 0
  # scheduler, 1x
  STEPS: (6000,)
  MAX_ITER: 9000
